#!/bin/bash
# Setup certificates for cryptic development

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CRYPTIC_ROOT="$(dirname "$SCRIPT_DIR")"
CA_DIR="$CRYPTIC_ROOT/CA"
CERT_DIR="$CRYPTIC_ROOT/priv/ssl"

echo "Setting up Cryptic certificates using myca..."

# Ensure CA directory exists and is initialized
if [ ! -d "$CA_DIR" ]; then
    echo "Error: CA directory not found. Run 'make CA' first."
    exit 1
fi

cd "$CA_DIR"

# Initialize CA if not already done
if [ ! -f "certs/ca.crt" ] || [ ! -f "certs/server.crt" ]; then
    echo "Initializing Certificate Authority..."
    make all
else
    echo "Certificate Authority already initialized"
fi

# Generate server certificate (already done by make all)
echo "Server certificate already generated by make all"

# Generate client certificates
echo "Generating client certificates..."
for user in alice bob charlie admin; do
    echo "  - Generating certificate for: $user"
    # Create non-interactive client certificate generation
    if [ ! -f "client_keys/${user}.crt" ]; then
        # Generate key
        openssl req -newkey ec -pkeyopt ec_paramgen_curve:secp384r1 \
            -keyout "client_keys/${user}.key" -nodes \
            -out "csr/${user}.csr" \
            -subj "/C=SE/ST=Stockholm/L=Ekero/O=Kruskakli/OU=client/CN=${user}/emailAddress=${user}@kruskakli.se"
        
        # Sign certificate
        openssl ca -config ./openssl.cnf -batch -notext \
            -in "csr/${user}.csr" -days 3652 \
            -out "client_keys/${user}.crt"
        
        # Create combined PEM file
        cat "client_keys/${user}.key" "client_keys/${user}.crt" > "client_keys/${user}.pem"
    fi
done

# Create cryptic ssl directory
mkdir -p "$CERT_DIR"

# Copy certificates to cryptic priv/ssl
echo "Copying certificates to cryptic/priv/ssl..."

# Server certificates
cp certs/ca.crt "$CERT_DIR/"
cp certs/server.crt "$CERT_DIR/server.crt"
cp private/server.key "$CERT_DIR/server.key"

# Client certificates
for user in alice bob charlie admin; do
    cp "client_keys/${user}.crt" "$CERT_DIR/client_${user}.crt"
    cp "client_keys/${user}.key" "$CERT_DIR/client_${user}.key"
    cp "client_keys/${user}.pem" "$CERT_DIR/client_${user}.pem"
done

echo "✅ Certificate setup complete!"
echo ""
echo "Server certificates:"
echo "  - CA: $CERT_DIR/ca.crt"
echo "  - Server cert: $CERT_DIR/server.crt"
echo "  - Server key: $CERT_DIR/server.key"
echo ""
echo "Client certificates:"
for user in alice bob charlie admin; do
    echo "  - ${user}: $CERT_DIR/client_${user}.pem"
done
