%%%-------------------------------------------------------------------
%%% @doc Client certificate issuance using Erlang public_key module
%%%
%%% Issues X.509 certificates for client authentication based on
%%% Certificate Signing Requests (CSRs). Uses the hybrid approach:
%%% - CA root certificate generated by myca (bootstrap)
%%% - Client certificates issued by Erlang public_key (runtime)
%%%
%%% This module handles:
%%% - CSR parsing and validation
%%% - Manual ASN.1 certificate construction (production-safe)
%%% - Certificate signing with CA private key
%%% - PEM encoding for distribution
%%%
%%% @end
%%%-------------------------------------------------------------------
-module(cryptic_ca_cert).

-include_lib("public_key/include/public_key.hrl").
-include("cryptic_ca.hrl").
-include("cryptic_server.hrl").

%% API
-export([
    issue_from_csr/2,
    issue_from_csr/3,
    issue_from_csr_with_gpg_proof/3,
    issue_from_csr_with_gpg_proof/4,
    parse_csr/1,
    validate_csr/1,
    build_client_cert/4,
    sign_cert/2,
    encode_pem/1
]).

%% OID constants
-define(SHA256_WITH_ECDSA, {1,2,840,10045,4,3,2}).
-define(ID_CE_KEY_USAGE, {2,5,29,15}).
-define(ID_CE_EXT_KEY_USAGE, {2,5,29,37}).
-define(ID_CE_SUBJECT_ALT_NAME, {2,5,29,17}).
-define(ID_KP_CLIENT_AUTH, {1,3,6,1,5,5,7,3,2}).
-define(CRYPTIC_GPG_FP_OID, {1,3,6,1,4,1,99999,1,1}). % Custom OID for GPG FP

%%%===================================================================
%%% API
%%%===================================================================

%% @doc Issue certificate from CSR with GPG fingerprint
%%
%% Main entry point for certificate issuance. Validates CSR,
%% builds certificate with proper extensions, signs with CA key,
%% and returns PEM-encoded certificate.
%%
%% Default validity: 7 days (configurable in sys.config)
%%
%% Example:
%% ```
%% CSR_PEM = <<"-----BEGIN CERTIFICATE REQUEST-----\n...">>,
%% GPG_FP = <<"ABCD1234...">>,
%% {ok, CertPEM} = cryptic_ca_cert:issue_from_csr(CSR_PEM, GPG_FP).
%% '''
-spec issue_from_csr(binary(), binary()) ->
    {ok, binary()} | {error, term()}.
issue_from_csr(CSR_PEM, GPG_FP) ->
    ValidityDays = application:get_env(cryptic,
                                       cert_default_lifetime_days,
                                       7),
    issue_from_csr(CSR_PEM, GPG_FP, ValidityDays).

%% @doc Issue certificate from CSR with custom validity period
-spec issue_from_csr(binary(), binary(), pos_integer()) ->
    {ok, binary()} | {error, term()}.
issue_from_csr(CSR_PEM, GPG_FP, ValidityDays) when ValidityDays > 0 ->
    try
        % Parse CSR
        {ok, CSR} = parse_csr(CSR_PEM),
        
        % Validate CSR
        ok = validate_csr(CSR),
        
        % Extract info from CSR
        #'CertificationRequestInfo'{
            subject = Subject,
            subjectPKInfo = SubjectPKInfo
        } = CSR#'CertificationRequest'.certificationRequestInfo,
        
        % Convert SubjectPKInfo to OTPSubjectPublicKeyInfo format
        OTPSubjectPKInfo = convert_subject_pk_info(SubjectPKInfo),
        
        % Load CA key (cert will be loaded in build_client_cert)
        {ok, CAKey} = application:get_env(cryptic, ca_key),
        
        % Build certificate
        {ok, Cert} = build_client_cert(Subject, OTPSubjectPKInfo, GPG_FP,
                                        ValidityDays),
        
        % Get serial before signing
        Serial = Cert#'OTPCertificate'.tbsCertificate#'OTPTBSCertificate'.serialNumber,
        
        % Sign certificate (returns DER-encoded)
        {ok, SignedCertDER} = sign_cert(Cert, CAKey),
        
        % Encode to PEM
        {ok, PEM} = encode_pem(SignedCertDER),
        
        ?info("Issued certificate for GPG FP ~s, serial ~p, valid ~p days",
              [GPG_FP, Serial, ValidityDays]),
        
        {ok, PEM}
        
    catch
        ErrorType:ErrorReason:Stack ->
            ?error("Failed to issue certificate: ~p:~p~n~p",
                   [ErrorType, ErrorReason, Stack]),
            {error, {cert_issuance_failed, ErrorReason}}
    end.

%% @doc Issue certificate from CSR with GPG signature proof
%%
%% This function implements the complete certificate issuance flow with
%% GPG signature verification as described in the onboarding protocol:
%%
%% 1. Verify GPG fingerprint exists in registry with verified status
%% 2. Fetch the stored GPG public key from registry
%% 3. Verify the GPG signature over the CSR
%% 4. Parse and validate the CSR (structural + cryptographic)
%% 5. Issue the certificate
%%
%% This ensures that:
%% - The requester is a registered user (GPG FP in registry)
%% - The requester proves possession of the GPG private key (signature)
%% - The CSR is well-formed and signed with TLS private key
%%
%% Default validity: 7 days (configurable in sys.config)
%%
%% Example:
%% ```
%% CSR_PEM = <<"-----BEGIN CERTIFICATE REQUEST-----\n...">>,
%% GPG_FP = <<"ABCD1234...">>,
%% GPG_SIG = <<"-----BEGIN PGP SIGNATURE-----\n...">>,
%% {ok, CertPEM} = cryptic_ca_cert:issue_from_csr_with_gpg_proof(
%%     CSR_PEM, GPG_FP, GPG_SIG).
%% '''
-spec issue_from_csr_with_gpg_proof(binary(), binary(), binary()) ->
    {ok, binary()} | {error, term()}.
issue_from_csr_with_gpg_proof(CSR_PEM, GPG_FP, GPG_Signature) ->
    ValidityDays = application:get_env(cryptic,
                                       cert_default_lifetime_days,
                                       7),
    issue_from_csr_with_gpg_proof(CSR_PEM, GPG_FP, GPG_Signature, ValidityDays).

%% @doc Issue certificate from CSR with GPG proof and custom validity
-spec issue_from_csr_with_gpg_proof(binary(), binary(), binary(), pos_integer()) ->
    {ok, binary()} | {error, term()}.
issue_from_csr_with_gpg_proof(CSR_PEM, GPG_FP, GPG_Signature, ValidityDays) 
    when ValidityDays > 0 ->
    try
        %% Step 1: Verify GPG fingerprint exists in registry
        case verify_gpg_identity(GPG_FP) of
            {ok, GPG_PubKey} ->
                %% Step 2: Verify GPG signature over CSR
                case cryptic_ca_gpg:verify_detached_signature(
                    CSR_PEM, GPG_Signature, GPG_PubKey) of
                    ok ->
                        %% Step 3: Issue certificate (this validates CSR internally)
                        case issue_from_csr(CSR_PEM, GPG_FP, ValidityDays) of
                            {ok, CertPEM} ->
                                ?info("Issued certificate for verified GPG FP ~s with proof",
                                      [GPG_FP]),
                                {ok, CertPEM};
                            {error, Reason} = Error ->
                                ?error("Certificate issuance failed after GPG verification: ~p",
                                       [Reason]),
                                Error
                        end;
                    {error, Reason} ->
                        ?warning("GPG signature verification failed for FP ~s: ~p",
                                 [GPG_FP, Reason]),
                        {error, {invalid_gpg_signature, Reason}}
                end;
            {error, Reason} = Error ->
                ?warning("GPG identity verification failed for FP ~s: ~p",
                         [GPG_FP, Reason]),
                Error
        end
    catch
        ErrorType:ErrorReason:Stack ->
            ?error("Failed to issue certificate with GPG proof: ~p:~p~n~p",
                   [ErrorType, ErrorReason, Stack]),
            {error, {cert_issuance_with_proof_failed, ErrorReason}}
    end.

%% @doc Verify GPG identity exists in registry and return public key
%% @private
-spec verify_gpg_identity(binary()) ->
    {ok, binary()} | {error, term()}.
verify_gpg_identity(GPG_FP) ->
    try
        %% Get database reference
        case application:get_env(cryptic, ca_db_ref) of
            {ok, DbRef} ->
                %% Check if GPG identity exists with verified status
                case cryptic_gpg_registry:get_identity(DbRef, GPG_FP) of
                    {ok, Identity} ->
                        %% Check status
                        Status = maps:get(status, Identity, undefined),
                        case Status of
                            <<"verified_via_invite">> ->
                                %% Return public key
                                GPG_PubKey = maps:get(gpg_pub_armor, Identity),
                                {ok, GPG_PubKey};
                            <<"verified_bootstrap">> ->
                                %% Return public key
                                GPG_PubKey = maps:get(gpg_pub_armor, Identity),
                                {ok, GPG_PubKey};
                            <<"pending">> ->
                                {error, gpg_identity_pending_verification};
                            <<"revoked">> ->
                                {error, gpg_identity_revoked};
                            _ ->
                                {error, {unknown_gpg_identity_status, Status}}
                        end;
                    {error, not_found} ->
                        {error, gpg_fingerprint_not_registered};
                    {error, Reason} = Error ->
                        ?error("Failed to lookup GPG identity ~s: ~p", [GPG_FP, Reason]),
                        Error
                end;
            undefined ->
                {error, ca_database_not_initialized}
        end
    catch
        ErrorType:ErrorReason:Stack ->
            ?error("Exception during GPG identity verification: ~p:~p~n~p",
                   [ErrorType, ErrorReason, Stack]),
            {error, {gpg_identity_verification_exception, ErrorReason}}
    end.

%% @doc Parse PEM-encoded CSR
-spec parse_csr(binary()) ->
    {ok, #'CertificationRequest'{}} | {error, term()}.
parse_csr(CSR_PEM) ->
    try
        % Decode PEM
        [{_, CSRDER, _}] = public_key:pem_decode(CSR_PEM),
        
        % Decode DER to CSR record
        CSR = public_key:der_decode('CertificationRequest', CSRDER),
        
        {ok, CSR}
    catch
        _:Reason ->
            ?error("Failed to parse CSR: ~p", [Reason]),
            {error, {csr_parse_failed, Reason}}
    end.

%% @doc Validate CSR structure and cryptographic signature
%%
%% Performs two levels of validation:
%% 1. Structural validation: Verifies all required fields are present
%% 2. Cryptographic validation: Verifies signature using public key from CSR
%%
%% This ensures the CSR was created by the holder of the private key
%% corresponding to the public key in the CSR.
-spec validate_csr(#'CertificationRequest'{}) -> ok | {error, term()}.
validate_csr(CSR) ->
    try
        % Validate CSR structure
        #'CertificationRequest'{
            certificationRequestInfo = Info,
            signatureAlgorithm = SigAlg,
            signature = Signature
        } = CSR,
        
        #'CertificationRequestInfo'{
            subject = Subject,
            subjectPKInfo = SubjectPKInfo
        } = Info,
        
        #'CertificationRequest_signatureAlgorithm'{
            algorithm = AlgOID
        } = SigAlg,
        
        % Basic sanity checks
        true = is_tuple(Subject),  % Subject must be present
        true = is_tuple(SubjectPKInfo),  % Public key info must be present
        true = is_binary(Signature),  % Signature must be binary
        true = byte_size(Signature) > 0,  % Signature must not be empty
        
        % Cryptographic signature verification
        case verify_csr_signature(Info, AlgOID, Signature, SubjectPKInfo) of
            ok -> ok;
            {error, _} = Err -> throw(Err)
        end,
        
        ok
        
    catch
        throw:{error, _} = ThrownError ->
            ThrownError;
        error:{badmatch, _} ->
            ?error("CSR structure validation failed: missing or invalid required fields", []),
            {error, invalid_csr_structure};
        ErrorType:ErrorReason:Stack ->
            ?error("CSR validation failed: ~p:~p~n~p", [ErrorType, ErrorReason, Stack]),
            {error, {csr_validation_failed, ErrorReason}}
    end.

%% @doc Build client certificate from CSR components
%%
%% Manual ASN.1 construction (production-safe, NOT test helpers).
%% Creates properly formatted X.509 certificate with:
%% - Unique serial number (from cryptic_ca_serial)
%% - Validity period (NotBefore/NotAfter)
%% - Subject from CSR
%% - Public key from CSR
%% - Extensions for TLS client auth
%% - GPG fingerprint in Subject Alternative Name
-spec build_client_cert(
    tuple(),  % Subject Name from CSR
    tuple(),  % SubjectPublicKeyInfo from CSR
    binary(),
    pos_integer()
) -> {ok, #'OTPCertificate'{}} | {error, term()}.
build_client_cert(Subject, SubjectPKInfo, GPG_FP, ValidityDays) ->
    try
        % Get next serial number
        SerialNum = cryptic_ca_serial:next(),
        
        % Calculate validity period
        Now = calendar:datetime_to_gregorian_seconds(
                calendar:universal_time()),
        ValiditySecs = ValidityDays * 86400,
        NotBefore = gregorian_to_utc_time(Now),
        NotAfter = gregorian_to_utc_time(Now + ValiditySecs),
        
        % Load CA cert to get issuer
        {ok, CACert} = application:get_env(cryptic, ca_cert),
        Issuer = extract_issuer(CACert),
        
        % Build certificate extensions
        Extensions = build_client_extensions(GPG_FP),
        
        % Construct TBSCertificate (To Be Signed)
        TBSCert = #'OTPTBSCertificate'{
            version = v3,
            serialNumber = SerialNum,
            signature = #'SignatureAlgorithm'{
                algorithm = ?SHA256_WITH_ECDSA,
                parameters = asn1_NOVALUE
            },
            issuer = Issuer,
            validity = #'Validity'{
                notBefore = {utcTime, NotBefore},
                notAfter = {utcTime, NotAfter}
            },
            subject = Subject,
            subjectPublicKeyInfo = SubjectPKInfo,
            extensions = Extensions
        },
        
        % Construct certificate (before signing)
        Cert = #'OTPCertificate'{
            tbsCertificate = TBSCert,
            signatureAlgorithm = TBSCert#'OTPTBSCertificate'.signature,
            signature = <<>> % Will be filled by pkix_sign
        },
        
        {ok, Cert}
        
    catch
        ErrorType:ErrorReason:Stack ->
            ?error("Failed to build certificate: ~p:~p~n~p",
                   [ErrorType, ErrorReason, Stack]),
            {error, {cert_build_failed, ErrorReason}}
    end.

%% @doc Sign certificate with CA private key (PRODUCTION SAFE)
%%
%% Uses public_key:pkix_sign/2 which is the production-safe way
%% to sign certificates. Does NOT use pkix_test_root_cert/2.
%%
%% Note: pkix_sign/2 expects TBSCertificate (not full OTPCertificate)
%% and returns DER-encoded signed certificate.
-spec sign_cert(#'OTPCertificate'{}, tuple()) ->
    {ok, binary()} | {error, term()}.
sign_cert(#'OTPCertificate'{tbsCertificate = TBSCert}, CAKey) ->
    try
        SignedCertDER = public_key:pkix_sign(TBSCert, CAKey),
        {ok, SignedCertDER}
    catch
        ErrorType:ErrorReason:Stack ->
            ?error("Failed to sign certificate: ~p:~p~n~p",
                   [ErrorType, ErrorReason, Stack]),
            {error, {cert_signing_failed, ErrorReason}}
    end.

%% @doc Encode DER certificate to PEM format
-spec encode_pem(binary()) -> {ok, binary()} | {error, term()}.
encode_pem(CertDER) when is_binary(CertDER) ->
    try
        % Encode DER to PEM
        PEM = public_key:pem_encode([{'Certificate', CertDER, not_encrypted}]),
        
        {ok, PEM}
    catch
        _:Reason ->
            ?error("Failed to encode certificate to PEM: ~p", [Reason]),
            {error, {pem_encoding_failed, Reason}}
    end.

%%%===================================================================
%%% Internal functions
%%%===================================================================

%% @private Convert CertificationRequestInfo_subjectPKInfo to OTPSubjectPublicKeyInfo
%%
%% Handles different public key algorithms (RSA, ECDSA, EdDSA, etc.) by
%% transforming from CSR format to OTP certificate format.
%%
%% Key algorithm-specific transformations:
%% - ECDSA/EdDSA: Wrap public key binary in ECPoint record, decode curve parameters
%% - RSA: Public key binary used as-is, parameters are NULL
%% - DSA: Public key binary used as-is, decode Dss-Parms
convert_subject_pk_info(
    {'CertificationRequestInfo_subjectPKInfo',
     {'CertificationRequestInfo_subjectPKInfo_algorithm', AlgOID, Params},
     PublicKey}) ->
    
    % Algorithm-specific parameter and key decoding
    {DecodedParams, SubjectPubKey} = case AlgOID of
        {1,2,840,10045,2,1} ->
            % id-ecPublicKey (ECDSA)
            % Params: EcpkParameters (namedCurve OID or explicit ECParameters)
            % Key: Must be wrapped in ECPoint record
            DecParams = decode_ec_params(Params),
            {DecParams, #'ECPoint'{point = PublicKey}};
            
        {1,3,101,112} ->
            % id-Ed25519 (EdDSA)
            % Params: NULL or absent
            % Key: Must be wrapped in ECPoint record
            {{namedCurve, AlgOID}, #'ECPoint'{point = PublicKey}};
            
        {1,3,101,113} ->
            % id-Ed448 (EdDSA)
            % Params: NULL or absent
            % Key: Must be wrapped in ECPoint record
            {{namedCurve, AlgOID}, #'ECPoint'{point = PublicKey}};
            
        {1,2,840,113549,1,1,1} ->
            % rsaEncryption
            % Params: NULL
            % Key: DER-encoded RSAPublicKey (will be decoded by OTP)
            {decode_params(Params, 'NULL'), PublicKey};
            
        {1,2,840,10040,4,1} ->
            % id-dsa
            % Params: Dss-Parms
            % Key: INTEGER (DSA public key Y value)
            {decode_params(Params, 'Dss-Parms'), PublicKey};
            
        _ ->
            % Unknown algorithm - pass through as-is
            % This allows forward compatibility with new algorithms
            ?warning("Unknown public key algorithm OID: ~p, using as-is", [AlgOID]),
            {decode_params(Params, undefined), PublicKey}
    end,
    
    #'OTPSubjectPublicKeyInfo'{
        algorithm = #'PublicKeyAlgorithm'{
            algorithm = AlgOID,
            parameters = DecodedParams
        },
        subjectPublicKey = SubjectPubKey
    }.

%% @private Verify CSR cryptographic signature
%%
%% Extracts the public key from the CSR, encodes the CertificationRequestInfo
%% to DER format, and verifies the signature matches.
verify_csr_signature(Info, AlgOID, Signature, SubjectPKInfo) ->
    try
        % Extract and format public key for verification
        PubKey = extract_public_key_for_verification(SubjectPKInfo),
        
        % Determine digest type from signature algorithm OID
        DigestType = sig_alg_to_digest_type(AlgOID),
        
        % Encode CertificationRequestInfo to DER (this is what was signed)
        InfoDER = public_key:der_encode('CertificationRequestInfo', Info),
        
        % Verify signature
        case public_key:verify(InfoDER, DigestType, Signature, PubKey) of
            true ->
                ok;
            false ->
                {error, invalid_csr_signature}
        end
    catch
        _:ErrorReason:_ ->
            {error, {csr_signature_verification_error, ErrorReason}}
    end.

%% @private Extract public key from CSR SubjectPKInfo in format suitable for verify/4
%%
%% Different algorithms require different formats:
%% - ECDSA/EdDSA: {#'ECPoint'{point = Binary}, {namedCurve, OID} | #'ECParameters'{...}}
%% - RSA: #'RSAPublicKey'{...} (decoded from binary)
%% - DSA: {Integer, #'Dss-Parms'{...}}
extract_public_key_for_verification(
    {'CertificationRequestInfo_subjectPKInfo',
     {'CertificationRequestInfo_subjectPKInfo_algorithm', AlgOID, Params},
     PublicKey}) ->
    
    case AlgOID of
        {1,2,840,10045,2,1} ->
            % id-ecPublicKey (ECDSA)
            % Return {#'ECPoint'{point = Binary}, Parameters}
            DecParams = decode_ec_params(Params),
            {#'ECPoint'{point = PublicKey}, DecParams};
            
        {1,3,101,112} ->
            % id-Ed25519 (EdDSA)
            {{namedCurve, AlgOID}, #'ECPoint'{point = PublicKey}};
            
        {1,3,101,113} ->
            % id-Ed448 (EdDSA)
            {{namedCurve, AlgOID}, #'ECPoint'{point = PublicKey}};
            
        {1,2,840,113549,1,1,1} ->
            % rsaEncryption
            % Decode the DER-encoded RSAPublicKey
            public_key:der_decode('RSAPublicKey', PublicKey);
            
        {1,2,840,10040,4,1} ->
            % id-dsa
            % Return {Y, Dss-Parms}
            DecParams = decode_params(Params, 'Dss-Parms'),
            YValue = public_key:der_decode('DSAPublicKey', PublicKey),
            {YValue, DecParams};
            
        _ ->
            % Unknown algorithm - try as-is
            ?warning("Unknown public key algorithm for verification: ~p", [AlgOID]),
            PublicKey
    end.

%% @private Map signature algorithm OID to digest type
sig_alg_to_digest_type({1,2,840,10045,4,3,2}) -> sha256;  % ecdsa-with-SHA256
sig_alg_to_digest_type({1,2,840,10045,4,3,3}) -> sha384;  % ecdsa-with-SHA384
sig_alg_to_digest_type({1,2,840,10045,4,3,4}) -> sha512;  % ecdsa-with-SHA512
sig_alg_to_digest_type({1,2,840,113549,1,1,11}) -> sha256;  % sha256WithRSAEncryption
sig_alg_to_digest_type({1,2,840,113549,1,1,12}) -> sha384;  % sha384WithRSAEncryption
sig_alg_to_digest_type({1,2,840,113549,1,1,13}) -> sha512;  % sha512WithRSAEncryption
sig_alg_to_digest_type({1,2,840,113549,1,1,5}) -> sha1;    % sha1WithRSAEncryption
sig_alg_to_digest_type({1,2,840,10040,4,3}) -> sha1;       % id-dsa-with-sha1
sig_alg_to_digest_type({2,16,840,1,101,3,4,3,2}) -> sha256; % id-dsa-with-sha256
sig_alg_to_digest_type({1,3,101,112}) -> none;  % Ed25519 (no separate hash)
sig_alg_to_digest_type({1,3,101,113}) -> none;  % Ed448 (no separate hash)
sig_alg_to_digest_type(OID) ->
    ?warning("Unknown signature algorithm OID: ~p, defaulting to sha256", [OID]),
    sha256.

%% @private Decode EC parameters (namedCurve or explicit ECParameters)
decode_ec_params({asn1_OPENTYPE, ParamsBin}) ->
    case public_key:der_decode('EcpkParameters', ParamsBin) of
        {namedCurve, CurveOID} -> {namedCurve, CurveOID};
        Other -> Other
    end;
decode_ec_params(Other) -> Other.

%% @private Generic parameter decoder
decode_params({asn1_OPENTYPE, _ParamsBin}, 'NULL') ->
    'NULL';  % RSA uses NULL parameters
decode_params({asn1_OPENTYPE, ParamsBin}, 'Dss-Parms') ->
    public_key:der_decode('Dss-Parms', ParamsBin);
decode_params({asn1_OPENTYPE, _ParamsBin}, undefined) ->
    asn1_NOVALUE;  % Unknown algorithm, use NOVALUE
decode_params(Other, _) -> Other.

%% @private Build extensions for client certificates
build_client_extensions(GPG_FP) ->
    % Create DNS name from GPG fingerprint for SAN
    DNSName = binary_to_list(<<GPG_FP/binary, ".gpg.cryptic.local">>),
    
    [
        % Key Usage: Digital Signature + Key Encipherment (critical)
        #'Extension'{
            extnID = ?ID_CE_KEY_USAGE,
            critical = true,
            extnValue = [digitalSignature, keyEncipherment]
        },
        
        % Extended Key Usage: TLS Client Authentication
        #'Extension'{
            extnID = ?ID_CE_EXT_KEY_USAGE,
            critical = false,
            extnValue = [?ID_KP_CLIENT_AUTH]
        },
        
        % Subject Alternative Name: GPG Fingerprint as DNS name
        % Format: <fingerprint>.gpg.cryptic.local
        #'Extension'{
            extnID = ?ID_CE_SUBJECT_ALT_NAME,
            critical = false,
            extnValue = [{dNSName, DNSName}]
        }
    ].

%% @private Extract issuer from CA certificate
extract_issuer(CACert) ->
    #'OTPCertificate'{
        tbsCertificate = #'OTPTBSCertificate'{
            subject = Subject
        }
    } = CACert,
    Subject.

%% @private Convert Gregorian seconds to UTCTime string
%% Format: YYMMDDHHMMSSZ
gregorian_to_utc_time(GregorianSecs) ->
    {{Y, M, D}, {H, Min, S}} =
        calendar:gregorian_seconds_to_datetime(GregorianSecs),
    
    % UTCTime uses 2-digit year
    YY = Y rem 100,
    
    lists:flatten(
        io_lib:format("~2..0B~2..0B~2..0B~2..0B~2..0B~2..0BZ",
                      [YY, M, D, H, Min, S])
    ).

